http:
  middlewares:
    crowdsec:
      plugin:
        bouncer:
          enabled: true
          logLevel: DEBUG
          crowdsecMode: live
          crowdsecLapiKey: {{ env "CROWDSEC_BOUNCER_API_KEY" }}
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiScheme: http
          clientTrustedIPs:
            - "100.64.0.0/10"
            - "172.16.0.0/12"
            - "192.168.50.0/24"
